#!/bin/sh
branch_name=$(git rev-parse --abbrev-ref HEAD)

if [ "${branch_name}" = "master" ]; then
    echo "master branch is dmmm"

elif [ "${branch_name}" = "dev" ]; then
    echo "dev branch is dm"

elif [ "${branch_name}" = "" ]; then
    echo "dev branch is null"

else
    git checkout dev
    git merge -Xtheirs "${branch_name}"
    git ftp push
    git checkout "${branch_name}"
    git push origin "${branch_name}"
fi
